export { default as SignIn } from './SignIn'
export { default as SignUp } from './SignUp'
export { default as SignInSide } from './SignInSide'
export { Blog } from './Blog'
export { Checkout } from './Checkout'
export { default as Album } from './Album'
export { default as Pricing } from './Pricing'
export { Dashboard } from './Dashboard'
